# ~/.zsh/zshrc

ZSH_CONFIG="$HOME/.zsh"

# Compile a list of additional files to be sourced
# From http://github.com/seebi/zshrc
typeset -ga sources

sources+="env.zsh"

# Zinit plugins
sources+="plugins.zsh"

sources+="aliases.zsh"
sources+="functions.zsh"
sources+="history.zsh"
sources+="misc.zsh"

sources+="keys.zsh"

sources+="private.zsh"

# note: paths.zsh and */modules.zsh are sourced from ~/.zshrc.local

# Homeshick
source "$HOME/.homesick/repos/homeshick/homeshick.sh"

for file in $sources; do
  if [[ -f $ZSH_CONFIG/$file ]]; then
    source "$ZSH_CONFIG/$file"
  fi
  if [[ -d $ZSH_CONFIG/$system_name ]]; then
    if [[ -f $ZSH_CONFIG/$system_name/$file ]]; then
      source "$ZSH_CONFIG/$system_name/$file"
    fi
  fi
done
