# ~/.zsh/zshrc

ZSH_CONFIG="$HOME/.zsh"

# Compile a list of additional files to be sourced
# From http://github.com/seebi/zshrc
typeset -ga sources
# OMZ customizations are used in antigen
sources+="oh-my.zsh"
# Antigen
sources+="antigen.zsh"
# Custom git plugin changes
sources+="git.zsh"

sources+="env.zsh"
sources+="aliases.zsh"
sources+="functions.zsh"
sources+="misc.zsh"

sources+="keys.zsh"

sources+="private.zsh"

# Homeshick
source "$HOME/.homesick/repos/homeshick/homeshick.sh"
fpath=($HOME/.homesick/repos/homeshick/completions $fpath)

for file in $sources; do
  if [[ -f $ZSH_CONFIG/$file ]]; then
    source "$ZSH_CONFIG/$file"
  fi
  if [[ -d $ZSH_CONFIG/$HOSTNAME ]]; then
    if [[ -f $ZSH_CONFIG/$HOSTNAME/$file ]]; then
      source "$ZSH_CONFIG/$HOSTNAME/$file"
    fi
  fi
done
